import Header from "@/components/header"
import type { Metadata } from "next"
import { DM_Sans, Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = DM_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = DM_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Logitech",
  description: "Generated by create next app",
  icons:{
    icon:"/logitech.png"
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased `}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}


